### ISSUE TITLE
Apps with multiple routes aliased to single source location error during hydration

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1124]
**Describe the issue**
Only happens in arc 8.5.4 and newer: if you have multiple lambdas set up to point to the same code location and try to `arc hydrate` them, things will blow up.

**Steps to reproduce**
1. Set up an arc app with the following arc manifest:

```
@app
invtest

@http
get /

/items
  method get
  src src/http/get-items
/api/v1/items
  method get
  src src/http/get-items
/api/v2/items
  method get
  src src/http/get-items

/artists
  method get
  src src/http/get-artists
/api/v2/artists
  method get
  src src/http/get-artists

/albums
  method get
  src src/http/get-albums
/api/v1/albums
  method get
  src src/http/get-albums
/api/v2/albums
  method get
  src src/http/get-albums
/api/v3/albums
  method get
  src src/http/get-albums
```

2. Run `arc init`
3. Create a `src/shared` directory and add something to it, e.g. `mkdir src/shared && touch src/shared/test.js`
4. Run `arc hydrate`
5. Watch explosions in your terminal:

```
11:01:17 in ~/src/invtest is 📦 v0.0.0 via ⬢ v14.14.0
➜ arc hydrate
         App ⌁ invtest
      Region ⌁ us-west-2
     Profile ⌁ default
     Version ⌁ Architect 8.5.5
         cwd ⌁ /Users/filmaj/src/invtest

⚬ Hydrate Hydrating app with shared files
/Users/filmaj/src/invtest/node_modules/@architect/hydrate/src/shared/get-paths.js:19
    let path = config.runtime.startsWith('nodejs') ? nodeModules : vendorDir
                      ^

TypeError: Cannot read property 'runtime' of undefined
    at /Users/filmaj/src/invtest/node_modules/@architect/hydrate/src/shared/get-paths.js:19:23
    at Array.forEach (<anonymous>)
    at getPaths (/Users/filmaj/src/invtest/node_modules/@architect/hydrate/src/shared/get-paths.js:11:58)
    at Array.<anonymous> (/Users/filmaj/src/invtest/node_modules/@architect/hydrate/src/shared/index.js:40:15)
    at each (/Users/filmaj/src/invtest/node_modules/run-series/index.js:20:24)
    at Array.<anonymous> (/Users/filmaj/src/invtest/node_modules/@architect/hydrate/src/shared/index.js:32:12)
    at runSeries (/Users/filmaj/src/invtest/node_modules/run-series/index.js:23:33)
    at shared (/Users/filmaj/src/invtest/node_modules/@architect/hydrate/src/shared/index.js:21:3)
    at Array.<anonymous> (/Users/filmaj/src/invtest/node_modules/@architect/hydrate/src/index.js:152:26)
    at runSeries (/Users/filmaj/src/invtest/node_modules/run-series/index.js:23:33)
```

## Additional Context

Seems to be related to an ever-increasing nesting inside inventory's `inv.lambdasBySrcDir` structure, where the nesting gets deeper the more lambdas are aliased to a single path. For example, for the `get-artists` routes using the above example app.arc, which has two lambdas aliased to `src/http/get-artists`, the value for `inv.lambdasBySrcDir['src/http/get-artists']` is:

```
"/Users/filmaj/src/invtest/src/http/get-artists": [
    {
      "name": "get /artists",
      "config": { ... },
    {
      "name": "get /api/v2/artists",
      "config": { ... },
    }
]
```

Looks good! But three routes to a single dir, like `get-items` in my example above?

```
"/Users/filmaj/src/invtest/src/http/get-items": [
    [
      {
        "name": "get /items",
        "config": { ... },
      },
      {
        "name": "get /api/v1/items",
        "config": { ... },
      }
    ],
    {
      "name": "get /api/v2/items",
      "config": { ... },
    }
  ]
```

The array nesting gets a little wonky.

**Comment by filmaj** [comment]
Just merged in the fix for this, should be live in arc 8.5.6 shortly!
