### ISSUE TITLE
`arc init` fatally errors when creating a project inside a directory with a space in the name

### ISSUE THREAD

**Issue by andybee** [architect/architect#1230]
**Describe the issue**
Because `init` uses the current directory's name to form the project name for `app.arc`, if you attempt to initiate a project in a directory with a space in the name, `init` generates a file with a project name that is invalid and fatally errors during the process.

**Steps to reproduce**
1. Create a enter a directory with a space in the name, such as `arc foo/`
2. Run `npm i @architect/architect`, then `npx arc init`.
3. See error that says:
```

     Version ⌁ Architect undefined
         cwd ⌁ /Users/andy/Desktop/arc example

✓ Create Created Architect project manifest (app.arc)
init failed! Validation error in app.arc:
- @app name not found or invalid
Error: Validation error in app.arc:
- @app name not found or invalid
    at format (/arc example/node_modules/@architect/inventory/src/lib/error-fmt.js:23:13)
    at architectInventory (/arc example/node_modules/@architect/inventory/src/index.js:80:14)
    at Object.cmd (/arc example/node_modules/@architect/create/cli.js:57:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (/arc example/node_modules/@architect/architect/src/index.js:55:5)
    at async main (/arc example/node_modules/@architect/architect/src/index.js:87:5)
    at async /arc example/node_modules/@architect/architect/src/index.js:96:5

```

**Expected behavior**
The project should be created successfully, with a sanitised name based on the directory that is valid. Alternatively, if `package.json` is available, could we use the name from that instead, which has similar constraints to `app.arc`?

**Desktop**
Not certain if this is relevant or not (OS specific directory naming weirdness?), but:
 - OS: macOS Catalina 10.15.7

**Comment by thescientist13** [comment]
Yeah, just wanted to chime in that I ran into a similar issue as well, where in the directory / repo name was modeled after a hostname for the project, e.g. api.mydomain.com.  (I'm sure I can change the name, just struck me as odd on first try)

Would love it if this pattern was honored as well.

**Comment by thescientist13** [comment]
Just wanted to loop back around on this one and see if it was still an open item or not, but seems it is.
```sh
➜  ~ mkdir www.myapp.com
➜  ~ cd www.myapp.com 
➜  www.myapp.com npm i @architect/architect
npm WARN deprecated @aws-sdk/node-http-handler@3.374.0: This package has moved to @smithy/node-http-handler
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 433 packages, and audited 434 packages in 30s

53 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  www.myapp.com npx arc init              

     Version ⌁ Architect 10.16.3
         cwd ⌁ /Users/.../www.myapp.com

✓ Create Created Architect project manifest (app.arc)
init failed! Validation error:
- Invalid @app item: 'www.myapp.com' must match /^[a-z][a-zA-Z0-9-_]+$/
Error: Validation error:
- Invalid @app item: 'www.myapp.com' must match /^[a-z][a-zA-Z0-9-_]+$/
    at format (/Users/.../www.myapp.com/node_modules/@architect/inventory/src/lib/error-fmt.js:15:13)
    at /Users/.../www.myapp.com/node_modules/@architect/inventory/src/index.js:92:18
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Just thought it was worth highlighting as its not uncommon for repo names like for documentation websites to be named after the hostname of the site itself, e.g **www.myapp.com**.  So relaxing this somehow would be great for those types of projects.   💯

**Comment by filmaj** [comment]
In the case of spaces in app name, I think [this part of `inventory`](https://github.com/architect/inventory/blob/main/src/config/pragmas/app.js#L5-L6) is at play: spaces in the app name means the `@app` pragma is an array with length > 1.

As for dots in the app name, that error comes from the same place during ["loose app name validation"](https://github.com/architect/inventory/blob/main/src/config/pragmas/app.js#L15) where "loose name" means [strings without dots](https://github.com/architect/inventory/blob/main/src/lib/index.js#L23).

I don't fully know the reasons for this constraint being in place. If it's for CloudFormation stack names, we already do removal of dashes and camel-casing the app name on dashes; I think we could do the same for spaces and for periods?
