### ISSUE TITLE
svelte kit app with @architect/sveltekit-adapter gives {"message":"Internal Server Error"}

### ISSUE THREAD

**Issue by mishrasatyam** [architect/architect#1279]
**Describe the issue**
Tried `@architect/sveltekit-adapter 0.0.4` adapter with svelte kit and I get `{"message":"Internal Server Error"}` after deploy

**Steps to reproduce**
1. Build a svelte kit app with `@architect/sveltekit-adapter` adapter
2. Deploy to staging on begin.com
3. Check staging url 
4. See error that says `{"message":"Internal Server Error"}`

**Expected behavior**
No error

**Logs from Begin.com HTTP routes**
```js
Unknown application error occurred
Runtime.UserCodeSyntaxError
```
```js
2021-11-26T05:26:20.448Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token '.'","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token '.'","    at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)","    at internal/main/run_main_module.js:17:47"]}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/31180325/143424642-b893b14c-4f2b-4ced-be96-da65c65f39ae.png)

**Additional context**
Also I got `@architect/functions` not found when trying `svelte-kit build` which should be mentioned in Readme of adapter.

**Comment by ryanbethel** [comment]
@mishrasatyam 
I am sorry you ran into trouble using the adapter. I am working on some updates. The Svelte Kit project is still in beta and the adapter API is still changing regularly. When it stabilizes we will try to update our adapter. In the meantime you might try your project with the @sveltejs/kit@1.0.0-next.147 just to see if it resolves the problem.

**Comment by mishrasatyam** [comment]
> @mishrasatyam I am sorry you ran into trouble using the adapter. I am working on some updates. The Svelte Kit project is still in beta and the adapter API is still changing regularly. When it stabilizes we will try to update our adapter. In the meantime you might try your project with the @sveltejs/kit@1.0.0-next.147 just to see if it resolves the problem.

I'll wait for the update then as current version is 201 , and makes no sense to test for version 147.
