### ISSUE TITLE
Unable to set an arc env var as a number

### ISSUE THREAD

**Issue by tbeseda** [architect/architect#1353]
with Architect 10.3.3
```bash
arc env --add --env staging MY_NUMBER "8675309"
```
gives me
```
env failed! Expected params.Value to be a string
InvalidParameterType: Expected params.Value to be a string
    at ParamValidator.fail (/my-project/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateType (/my-project/node_modules/aws-sdk/lib/param_validator.js:232:10)
    at ParamValidator.validateString (/my-project/node_modules/aws-sdk/lib/param_validator.js:154:32)
    at ParamValidator.validateScalar (/my-project/node_modules/aws-sdk/lib/param_validator.js:130:21)
    at ParamValidator.validateMember (/my-project/node_modules/aws-sdk/lib/param_validator.js:94:21)
    at ParamValidator.validateStructure (/my-project/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/my-project/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/my-project/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/my-project/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/my-project/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
```

For now I'm adding spaces and accounting for that in my function:
```bash
arc env --add --env staging MY_NUMBER " 8675309 "
```
```js
const myNumber = process.env.MY_NUMBER.trim();
```

**Comment by ryanblock** [comment]
Fixed in 10.3.4!
