### ISSUE TITLE
`spawn E2BIG` error on github actions with large arc file due to passing inventory using env vars

### ISSUE THREAD

**Issue by geramunoz** [architect/architect#1355]
**Describe the issue**

I'm running a test workflow on github actions and I'm getting a "spawn E2BIG" error, this occurs when sandbox tries to run the startup scripts, it seems my project reached a size large enough to exceed the maximum size allowed for arguments in a function
```
...
✓ Sandbox Started in 21ms
❤︎ Local environment ready!
⚬ Sandbox Running startup scripts
internal/child_process.js:408
    throw errnoException(err, 'spawn');
    ^
Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:677:9)
    at Object.execFile (child_process.js:311:17)
    at exec (child_process.js:212:25)
    at Array.<anonymous> (/home/runner/work/e2big-error-example/e2big-error-example/node_modules/@architect/sandbox/src/sandbox/startup-scripts.js:24:9)
    at runSeries (/home/runner/work/e2big-error-example/e2big-error-example/node_modules/run-series/index.js:23:33)
    at startupScripts (/home/runner/work/e2big-error-example/e2big-error-example/node_modules/@architect/sandbox/src/sandbox/startup-scripts.js:36:5)
    at Array.<anonymous> (/home/runner/work/e2big-error-example/e2big-error-example/node_modules/@architect/sandbox/src/sandbox/index.js:105:7)
    at each (/home/runner/work/e2big-error-example/e2big-error-example/node_modules/run-series/index.js:20:24)
    at startupSeedData (/home/runner/work/e2big-error-example/e2big-error-example/node_modules/@architect/sandbox/src/sandbox/seed.js:11:48) {
  errno: -7,
  code: 'E2BIG',
  syscall: 'spawn'
}
```

**Steps to reproduce**

Here is an example project
https://github.com/geramunoz/e2big-error-example/runs/7221735296?check_suite_focus=true

**Additional context**

It seems that what is causing the problem is a variable that contains the entire project context `ARC_INV` and is used together with the startup commands

https://github.com/architect/sandbox/blob/77e69966d3d635e61930bef33d7a15455d2c5269/src/sandbox/startup-scripts.js#L17

The  PR of the change that included `ARC_INV`
https://github.com/architect/sandbox/pull/597

**Comment by geramunoz** [comment]
@ryanblock yes it's an approximation and I was also able to identify that the argument passed to [child_process.exec](https://github.com/architect/sandbox/blob/156337bbb6b6e9ea1cedd2a57ce6306ae09f7b4b/src/sandbox/startup-scripts.js#L24) it has to be less than 140-150 KB approx, so that GHA doesn't blows up

**Comment by ryanblock** [comment]
So this works for me locally, and I assume you as well. So it sounds like perhaps this is a memory or environment limitation of some kind? Any theories as to why this would be happening specifically in GitHub Actions?

**Comment by geramunoz** [comment]
yep works locally, wasn't sure if this was a GHA specific problem, suspected it might be a problem with virtual environments, but then tried to test on another CI and it works fine too, so I'm going to assume the problem just happens in actions, I'm going to go there with my problem to see how to solve it definitively

**Comment by geramunoz** [comment]
meanwhile I'm going to make a sandbox fork, my idea is to reverse this https://github.com/architect/sandbox/pull/597, so I can avoid the error in actions

**Comment by ryanblock** [comment]
I wonder if it's simply just a very low memory container. Given what we know thus far, that would make this pretty difficult to detect and deal with; I suppose we could handle that specific error and retry scripts without the env var?

**Comment by ryanblock** [comment]
Any further thoughts on this?

**Comment by geramunoz** [comment]
Sorry I've been a little busy this last week, What I have managed to find out so far is that the problem is related to an ARG_MAX/NCARGS limit defined in the kernel, after version 2.6.23 of the linux kernel, this variable is no longer used as a static limit but rather defines the lower acceptable limit, and the total size of the parameters is now determined by 1/4 of the stack size, [more info here](https://www.in-ulm.de/~mascheck/various/argmax/).
There are some suggestions to determine the available space for the total length of the parameters, but the most reliable way to get the available space currently is to test the success of the exec() with an increasing argument length until it fails (I haven't done that yet), anyway theoretically the ubuntu latest image(the one I've been using to test) should have 2048 kb available, but for some reason this fails with a much smaller size approx 165 kb. In fact this problem is consistent in [circleci](https://app.circleci.com/pipelines/github/geramunoz/e2big-error-example/20/workflows/88b14070-6e8d-4031-bc43-2f0b39773aec/jobs/20), previously I couldn't make it fail, since it seems to have a little more space available (20 kb) than the ubuntu image used by GHA, then increasing the path definition in app.arc a little this failed

**Comment by ryanblock** [comment]
This is fascinating. While it's technically feasible for Architect to tests for this, doing so would be quite expensive. Thinking the solution I outlined here (https://github.com/architect/architect/issues/1355#issuecomment-1182688154) is still probably the right approach – or at least the only one that comes to mind that won't break things or slow down Sandbox's startup routines.
