### ISSUE TITLE
Deploy may wrongfully infer `@http` from `@static`

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1359]
**Describe the issue**
When deploying a project with `@static` pragma and no `@http` pragma (and no HTTP setter plugins), Deploy may blow up with the following error:
```
TypeError: Cannot destructure property 'src' of 'get.http(...)' as it is null.
    at asapFingerprint (/Users/ryan/git/architect/deploy/src/sam/patches/asap.js:15:11)
    at /Users/ryan/git/architect/deploy/src/sam/index.js:121:11
    at done (/Users/ryan/git/architect/deploy/node_modules/@architect/utils/fingerprint/index.js:148:10)
    at end (/Users/ryan/git/architect/deploy/node_modules/run-waterfall/index.js:11:18)
    at done (/Users/ryan/git/architect/deploy/node_modules/run-waterfall/index.js:14:10)
```

Deploy should not assume that projects with `@static` also have `@http` pragmas.

**Comment by ryanblock** [comment]
Fixed in Deploy 4.1.4!
