### ISSUE TITLE
Copy static.json fails if shared folder doesn't exist

### ISSUE THREAD

**Issue by macdonst** [architect/architect#1367]
**Describe the issue**

With the commit https://github.com/architect/inventory/commit/ae1a1219e1d6b261a3aceb2502c3464a17b3272b inventory no longer complains if the shared folder doesn't exits. However, if you run sandbox it errors out when it tries to create the static.json file.

The error:

```
Error:
    at Object.mkdirSync (fs.js:1013:3)
    at mkdirSync (pkg/prelude/bootstrap.js:1508:33)
    at copy (/snapshot/cli/node_modules/@architect/hydrate/src/shared/copy.js:16:5)
    at Array.copier (/snapshot/cli/node_modules/@architect/hydrate/src/shared/copy-static-json.js:33:9)
    at runSeries (/snapshot/cli/node_modules/run-series/index.js:23:33)
    at copyStatic (/snapshot/cli/node_modules/@architect/hydrate/src/shared/copy-static-json.js:31:5)
    at Array.<anonymous> (/snapshot/cli/node_modules/@architect/hydrate/src/shared/index.js:59:7)
    at each (/snapshot/cli/node_modules/run-series/index.js:20:24)
    at print (/snapshot/cli/node_modules/@architect/hydrate/src/_printer.js:66:10)
    at _done (/snapshot/cli/node_modules/@architect/hydrate/src/shared/copy-views.js:39:12)
```

**Steps to reproduce**

- clone the Begin CLI project at 42c5300eb35b3cc2940fd611f4799b7b519568dc. Later versions of the CLI detect the missing folder and create it on `begin dev`.
- build a version of the Begin CLI with inventory 3.2.1
- `begin new project --path today`
- `cd today`
- `rm -rf models`
- `begin dev`

**Expected behavior**
A clear and concise description of what you expected to happen

Hydrate shouldn't throw an error or it should produce a log that explains to the user how to work around their issue.

**Screenshots**
If applicable, add screenshots to help explain your problem

n/a

**Comment by ryanblock** [comment]
Fixed in Hydrate 3.0.6, thank you!
