### ISSUE TITLE
Hydrate conflict with Enhance starter project

### ISSUE THREAD

**Issue by ryanbethel** [architect/architect#1370]
**Describe the issue**
If you create an enhance starter project and try to deploy it it will fail. 

**Steps to reproduce**
Follow steps in [the guide](https://staging.enhance.dev/docs/learn/deployment/architect)
1. npm create @enhance ./my-enhance-project
2. cd my-enhance-project
3. npm install
4. npm start
5. arc deploy

**Clues**
running `arc deploy --no-hydrate` works

**Errors**
```
 my-enhance-project arc deploy
         App ⌁ myproj
      Region ⌁ us-west-2
     Profile ⌁ default
     Version ⌁ Architect 10.5.0
         cwd ⌁ /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/enh-getting-started/my-enhance-project

⚠️ Warning: Dynamic imports are not supported, dependency may not be installed: /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/enh-getting-started/my-enhance-project/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall imports 'pathToHead'
⚠️ Warning: Dynamic imports are not supported, dependency may not be installed: /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/enh-getting-started/my-enhance-project/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall imports 'pathToModule'
⚠️ Warning: Dynamic imports are not supported, dependency may not be installed: /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/enh-getting-started/my-enhance-project/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall imports 'apiPath'
× Error: JS parsing error(s), could not automatically determine dependencies
File: /Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/enh-getting-started/my-enhance-project/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/_get-elements.mjs
TypeError: Cannot read properties of null (reading 'value')
    at /Users/ryanbethel/.nvm/versions/node/v16.13.1/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/actions/autoinstall/find-lambda-deps.js:30:18
    at Array.forEach (<anonymous>)
    at getIdentifier (/Users/ryanbethel/.nvm/versions/node/v16.13.1/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/actions/autoinstall/find-lambda-deps.js:29:9)
    at /Users/ryanbethel/.nvm/versions/node/v16.13.1/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/actions/autoinstall/find-lambda-deps.js:46:37
    at Array.forEach (<anonymous>)
    at findLambdaDeps (/Users/ryanbethel/.nvm/versions/node/v16.13.1/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/actions/autoinstall/find-lambda-deps.js:35:11)
    at /Users/ryanbethel/.nvm/versions/node/v16.13.1/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/actions/autoinstall/get-lambda-deps.js:23:22
    at Array.forEach (<anonymous>)
    at getDirDeps (/Users/ryanbethel/.nvm/versions/node/v16.13.1/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/actions/autoinstall/get-lambda-deps.js:21:9)
    at /Users/ryanbethel/.nvm/versions/node/v16.13.1/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/actions/autoinstall/index.js:42:20
```

**Comment by ryanblock** [comment]
Fixed in https://github.com/architect/hydrate/pull/161 / Arc 10.5.2, thank you!
