### ISSUE TITLE
Deploy fails if no lambda source directories used

### ISSUE THREAD

**Issue by ryanbethel** [architect/architect#1378]
When trying to deploy after removing a problematic plugin I removed the deploy failed with the following:

```
deploy failed! Cannot read properties of null (reading 'length')
TypeError: Cannot read properties of null (reading 'length')
    at writeArcConfigs (/Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/enhance.dev/node_modules/@architect/create/src/write-configs/index.js:20:26)
    at create (/Users/ryanbethel/_PARA_Local/code-projects/consulting/begin-com/enhance.dev/node_modules/@architect/create/src/index.js:93:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The line of code that fails is:
```
 if (!inv.lambdaSrcDirs.length) return dirs
```

I added optional chaining and the deploy succeeded.

That may be the fix but I wanted to record the issue since I don't have time to do more to investigate at the moment.

**Comment by filmaj** [comment]
Going to close this as repro steps are light and it's been a while, but if you have repro steps feel free to re-open!
