### ISSUE TITLE
Cold deploy fails

### ISSUE THREAD

**Issue by remy** [architect/architect#1380]
**Describe the issue**

Followed the getting start guide and the deploy part just fails. I've included a full log of my shell below.

**Steps to reproduce**
1. `npm init @architect mocked`
2. `cd mocked`
3. `npx arc deploy`
4. Then I got the errors

<details><summary><strong>full log</strong></summary>
<pre><code>$ npx arc deploy                                                     
         App ⌁ mocked
      Region ⌁ us-west-2
     Profile ⌁ default
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/remy/dev/mocked

✓ Hydrate Finished checks, nothing to hydrate
⚬ Deploy Creating new private deployment bucket: mocked-cfn-deployments-6d101

⚬ Deploy Initializing deployment
  | Stack ... MockedStaging
  | Bucket .. mocked-cfn-deployments-6d101
⚬ Deploy Created deployment templates
✓ Deploy Generated CloudFormation deployment
Uploading to 6fa6d458959c1b3f03c7c62cc94d778d.template  5800 / 5800.0  (100.00%)
Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name MockedStaging

Uploading to 6fa6d458959c1b3f03c7c62cc94d778d.template  5800 / 5800.0  (100.00%)
Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name MockedStaging

    at ChildProcess.<anonymous> (/Users/remy/dev/mocked/node_modules/@architect/deploy/src/sam/utils/spawn.js:23:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:313:12)

$ aws cloudformation describe-stack-events --stack-name MockedStaging

An error occurred (ValidationError) when calling the DescribeStackEvents operation: Stack [MockedStaging] does not exist
</code></pre></details>

**Desktop**
Please complete the following information (if appropriate):
 - OS: macOS Big Sur 11.7 (20G817)

**Comment by tbeseda** [comment]
Hi @remy -- sorry it didn't work off the bat here. I wonder if AWS was having an issue. I was able to run the same process and got a successful deployment (albeit slower than normal)

```
         App ⌁ new-arc-10-7
      Region ⌁ us-west-2
     Profile ⌁ default
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/tbeseda/dev/scratch/new-arc-10-7

⚬ Hydrate Hydrating dependencies in 1 path
✓ Hydrate Hydrated src/http/get-index/
  ...
✓ Deploy Deployed & built infrastructure
✓ Success! Deployed app in 108.373 seconds
```

The only thing odd other than the failure in your logs is that `Uploading to... Waiting for...` portion occurred twice.

The error you're seeing from the `aws` command means the stack wasn't even created.

I suppose you could try again to rule out the AWS issue.

**Comment by ryanblock** [comment]
Hmm, unfortunately I too am unable to reproduce this. (See below.)

What happens if you try running it again now (where the only thing that's changed is time has elapsed 🙃)?

Also Brian's suggestion may be something to check too!

<details>
<code><pre>
✓ [08:47:29] (╯ಠ益ಠ)╯︵~/git/architect/_test-projects
⮑  npm init @architect mocked

     Version ⌁ Architect Create 4.1.1
         cwd ⌁ /Users/ryan/git/architect/_test-projects

⚬ Create Bootstrapping new Architect project
  | Project name .. mocked
  | Creating in ... /Users/ryan/git/architect/_test-projects/mocked
✓ Create Created Architect project manifest (app.arc)
✓ Create Created new project files in mocked/src/http/get-index/
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
⚬ Create Installing Architect...

added 267 packages, and audited 268 packages in 12s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

✓ Create Your Architect project is ready! Get started with: npx arc sandbox
✓ [08:47:44] (╯ಠ益ಠ)╯︵~/git/architect/_test-projects
⮑  cd mocked
✓ [08:47:46] (╯ಠ益ಠ)╯︵~/git/architect/_test-projects/mocked
⮑  npx arc deploy
         App ⌁ mocked
      Region ⌁ us-west-2
     Profile ⌁ default
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/ryan/git/architect/_test-projects/mocked

✓ Hydrate Finished checks, nothing to hydrate
⚬ Deploy Creating new private deployment bucket: mocked-cfn-deployments-67e0d
⚬ Deploy Initializing deployment
  | Stack ... MockedStaging
  | Bucket .. mocked-cfn-deployments-67e0d
⚬ Deploy Created deployment templates
✓ Deploy Generated CloudFormation deployment
⚬ Deploy Deploying static assets...
⚬ Deploy @static folder (public/) not found, skipping static asset deployment
✓ Deploy Deployed & built infrastructure
✓ Success! Deployed app in 105.672 seconds

    https://nchviavep5.execute-api.us-west-2.amazonaws.com
</code></pre>
</details>

**Comment by remy** [comment]
Tried with @brianleroux's suggestion - no dice:

<details>
$ npx arc deploy
         App ⌁ mocked
      Region ⌁ us-west-2
     Profile ⌁ default
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/remy/dev/mocked

✓ Hydrate Finished checks, nothing to hydrate
⚬ Deploy Initializing deployment
  | Stack ... MockedStaging
  | Bucket .. mocked-cfn-deployments-6d101
⚬ Deploy Created deployment templates
✓ Deploy Generated CloudFormation deployment
Uploading to 4dd16271e6354934c3616c4869b3f9b0.template  5800 / 5800.0  (100.00%)
An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-west-2:596019491244:stack/MockedStaging/9f91f240-456c-11ed-b481-0284f74e1693 is in ROLLBACK_COMPLETE state and can not be updated.

Uploading to 4dd16271e6354934c3616c4869b3f9b0.template  5800 / 5800.0  (100.00%)
An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-west-2:596019491244:stack/MockedStaging/9f91f240-456c-11ed-b481-0284f74e1693 is in ROLLBACK_COMPLETE state and can not be updated.

    at ChildProcess.<anonymous> (/Users/remy/dev/mocked/node_modules/@architect/deploy/src/sam/utils/spawn.js:23:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:313:12)

❯ echo $AWS_REGION
us-west-2
$ echo $AWS_PROFILE
default
$
</details>

**Comment by remy** [comment]
Also, I'm 100% sure it's me and not the default install! I know this, just not sure what could be missing…

**Comment by ryanblock** [comment]
Is it possible your local default credentials don't have all the permissions necessary to ship an app? Shorcut: make sure the role has `administratorAccess` in IAM.

**Comment by remy** [comment]
Is there any way to confirm this from the command line? 

Otherwise this is the access I've configured for the user:

![SCR-20221007-db8](https://user-images.githubusercontent.com/13700/194510291-9c49ab9e-1dab-4680-b4ca-5580b64ef7f9.png)

**Comment by remy** [comment]
Okay, I think I've gotten further. I was using [Leapp](https://www.leapp.cloud/) and I'm fairly sure it was messing things up. So I trashed it and ran `aws configure` again and the deploy got further.

But now I wonder if the deploy has gotten in a half baked state…

<details>
<summary>Details</summary>

<pre><code>
$ npx arc deploy
         App ⌁ mocked
      Region ⌁ us-west-2
     Profile ⌁ arc.code
     Version ⌁ Architect 10.7.0
         cwd ⌁ /Users/remy/dev/mocked

✓ Hydrate Finished checks, nothing to hydrate
⚬ Deploy Initializing deployment
  | Stack ... MockedStaging
  | Bucket .. mocked-cfn-deployments-6d101
⚬ Deploy Created deployment templates
✓ Deploy Generated CloudFormation deployment
Uploading to 66450ca3d0389812ed4a6f6beba5366d.template  5800 / 5800.0  (100.00%)
An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-west-2:596019491244:stack/MockedStaging/9f91f240-456c-11ed-b481-0284f74e1693 is in ROLLBACK_COMPLETE state and can not be updated.

Uploading to 66450ca3d0389812ed4a6f6beba5366d.template  5800 / 5800.0  (100.00%)
An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-west-2:596019491244:stack/MockedStaging/9f91f240-456c-11ed-b481-0284f74e1693 is in ROLLBACK_COMPLETE state and can not be updated.

    at ChildProcess.<anonymous> (/Users/remy/dev/mocked/node_modules/@architect/deploy/src/sam/utils/spawn.js:23:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:313:12)
</code></pre>

</details>

Any ideas how I can reset the aws state?

**Comment by remy** [comment]
Okay, solved it (appreciate many/all of you aren't on the UK TZ) - found cloudformation in AWS and deleted the things I found - reployed and it went up.

Cheers so much.

I'm fairly sure the original issue was down to my using Leapp to change my profiles. Lesson learnt - I need to stick to the CLI where I'm actually more effective!
