### ISSUE TITLE
Adding env var fails if other pre-existing env var contains semi colons

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1430]
**Describe the issue**
I have a long-standing arc project that has spanned many major versions of architect. I love the stability architect provides; thank you!

For many of these major versions of architect, I never used a `preferences.arc` file (I only had a single env var in this project, so I didn't feel the need to use the file).
Recently, I had to work with more env vars, and the `arc env` command would (somewhat annoyingly) keep prompting me to create a `preferences.arc` file. Finally, I got fed up and told it, sure, create the file, whatever.
Then, when I went to add a new env var, I saw this error:

```
➜ ./node_modules/.bin/arc env --add -e staging SOME_VAR something
env failed! Plugin error:
- Problem reading preferences.arc: unknown character ";" (line: 7 column: 57)
Error: Plugin error:
- Problem reading preferences.arc: unknown character ";" (line: 7 column: 57)
    at format (/Users/filmaj/src/arc-oss-contributors/node_modules/@architect/inventory/src/lib/error-fmt.js:15:13)
    at /Users/filmaj/src/arc-oss-contributors/node_modules/@architect/inventory/src/index.js:80:18
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

The one env var that has been present in the project for a long time indeed has semi-colon-delimited strings. It looks like this:

```
➜ cat preferences.arc
# The @env pragma is synced (and overwritten) by running arc env
@env
# testing
  # Add testing env vars with: arc env --add --env testing NAME value

staging
  SECRET_TOKENS secret1;secret2;secret3;secret4;
```

**Steps to reproduce**
1. `arc init` a project
2. `arc env --add -e staging SOMETHING "hey;ho;"`
3. answer 'yes' when `env` prompts you to create a `preferences.arc` file
4. `arc env --add -e staging OTHER hi`
5. explosion

**Expected behavior**
`preferences.arc` supports env vars with semi colons in it

**Additional context**

- Using arc 10.12.5
- If I edit the `preferences.arc` file and surround the variable value in question with double quotation marks, it fixes the issue, but only for one execution. The next time I go to run `arc env` the same issue will happen.

**Comment by filmaj** [comment]
This is still happening in arc 11.2. Dug in a bit more, and the error in the stack trace comes from the parser, which I found surprising: https://github.com/architect/parser/blob/main/src/errors/lex-unknown.js#L3
