### ISSUE TITLE
hydrate undefined error for multiple paths on direct deploy

### ISSUE THREAD

**Issue by kenhorn** [architect/architect#1455]
**Describe the issue**
./node_modules/@architect/hydrate/src/hydrate.js:123
      if (lambdaHasManifest && lambda.config.runtime.startsWith('nodejs')) {
                                             ^
TypeError: Cannot read properties of undefined (reading 'runtime')
    at ./node_modules/@architect/hydrate/src/hydrate.js:123:46

v10.10.3

If my app.arc contains two paths for a single source dir, ie:

/foo
  method post
  src    src/http/post-foo

/foo-noauth
  method post
  src    src/http/post-foo

I get the above error for direct deploys, but a normal deploy is fine. The lambda object has no config member, as in the above scenario it's an array of configs. Presumably something isn't calling .flatten() or similar for direct deploys.

Removing the second path's setup works as a workaround in dev.

**Steps to reproduce**
4. See error that says '....'

**Expected behavior**
A function should be deployed per normal / full deploy

**Screenshots**
If applicable, add screenshots to help explain your problem

**Desktop**
Please complete the following information (if appropriate):

**Mobile**
Please complete the following information (if appropriate):

**Additional context**
Add any other context or notes about the problem here

**Comment by filmaj** [comment]
Using arc 11.2, I get a different error, but probably same underlying issue:

```
⚠️ Warning: Direct deployments should be considered temporary, and will be overwritten
⚬ Deploy Initializing direct deployment
  | Stack ... StattestStaging
⚬ Deploy Deploying directly to: get /index (src/http/get-index)
⚬ Deploy Deploying directly to: get / (src/http/get-index)
⚬ Hydrate Hydrating dependencies in 1 path
⚬ Hydrate Hydrating dependencies in 1 path
✓ Hydrate Hydrated src/http/get-index/
  | npm ci --omit=dev: added 19 packages, and audited 20 packages in 529ms
  | npm ci --omit=dev: 3 packages are looking for funding
  | npm ci --omit=dev: run `npm fund` for details
  | npm ci --omit=dev: found 0 vulnerabilities
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with shared: src/shared
✓ Hydrate Hydrated app with static.json
✓ Hydrate Successfully hydrated dependencies
✓ Hydrate Hydrated src/http/get-index/
  | npm ci --omit=dev: added 19 packages, and audited 20 packages in 538ms
  | npm ci --omit=dev: 3 packages are looking for funding
  | npm ci --omit=dev: run `npm fund` for details
  | npm ci --omit=dev: found 0 vulnerabilities
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with shared: src/shared
✓ Hydrate Hydrated app with static.json
✓ Hydrate Successfully hydrated dependencies
✓ Deploy Published code to Lambda
deploy failed! @aws-lite/client: Lambda.UpdateFunctionCode: Conflict due to concurrent requests on this function. Please try this request again.
```

I guess this error makes sense in a way: `deploy` is trying to publish _twice_ to the same lambda, so it ends up stepping on its own toes.

Maybe there's a way to de-dupe the list of lambdas to direct deploy as a means of addressing this issue.

**Comment by filmaj** [comment]
Additionally, if I then try to re-run the direct deploy after the above error, I get this error, which points to `hydrate` also stepping on its own toes in this scenario:

```
⚠️ Warning: Direct deployments should be considered temporary, and will be overwritten
⚬ Deploy Initializing direct deployment
  | Stack ... StattestStaging
⚬ Deploy Deploying directly to: get /index (src/http/get-index)
⚬ Deploy Deploying directly to: get / (src/http/get-index)
⚬ Hydrate Hydrating dependencies in 1 path
⚬ Hydrate Hydrating dependencies in 1 path
✓ Hydrate Hydrated src/http/get-index/
  | npm ci --omit=dev: added 19 packages, and audited 20 packages in 580ms
  | npm ci --omit=dev: 3 packages are looking for funding
  | npm ci --omit=dev: run `npm fund` for details
  | npm ci --omit=dev: found 0 vulnerabilities
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated src/http/get-index/
  | npm ci --omit=dev: added 19 packages, and audited 20 packages in 571ms
  | npm ci --omit=dev: 3 packages are looking for funding
  | npm ci --omit=dev: run `npm fund` for details
  | npm ci --omit=dev: found 0 vulnerabilities
⚬ Hydrate Hydrating app with shared files
⚬ Hydrate Hydrated app with shared: src/shared
× Error: EEXIST: file already exists, mkdir '/Users/filmaj/src/stattest/src/http/get-index/node_modules/@architect/shared'
Error:
    at async mkdir (node:internal/fs/promises:857:10)
    at async mkDirAndCopy (node:internal/fs/cp/cp:308:3)
deploy failed! hydration_error
Error: hydration_error
    at print (/Users/filmaj/src/stattest/node_modules/@architect/hydrate/src/_printer.js:65:23)
    at _done (/Users/filmaj/src/stattest/node_modules/@architect/hydrate/src/shared/copy-shared.js:38:16)
```
