### ISSUE TITLE
Cannot locate plugin in `src/plugins` sub-directory when using MJS

### ISSUE THREAD

**Issue by andybee** [architect/architect#1478]
**Describe the issue**
If you author a plugin as a module at `src/plugins/my-plugin/index.mjs`, it will fail to load. This behaviour differs from authoring common JS in the same structure (e.g. `src/plugins/my-plugin/index.js`) or authoring a module at `src/plugins/my-plugin.mjs`. 

**Steps to reproduce**
1. Checkout [example project](https://github.com/andybee/arc-plugins-mjs-bug).
2. `npm install`
3. `npx arc sandbox`
4. See error that says "Cannot find plugin 'dir-mjs-errors'! Are you sure you have installed or created it correctly?"

**Expected behavior**
I would expect module JS plugins to work the same as common JS when inside a directory.

**Comment by filmaj** [comment]
Confirmed still an issue in arc 11.2:

```
➜ l src/plugins/nodelete
total 4.0K
drwxr-xr-x 3 filmaj staff  96 Mar 25 22:29 .
drwxr-xr-x 3 filmaj staff  96 Mar 23 22:20 ..
-rw-r--r-- 1 filmaj staff 935 Mar 25 22:29 index.mjs
➜ npx arc deploy --dry-run --no-hydrate
deploy failed! Plugin error:
- Cannot find plugin 'nodelete'! Are you sure you have installed or created it correctly?
Error: Plugin error:
- Cannot find plugin 'nodelete'! Are you sure you have installed or created it correctly?
    at format (/Users/filmaj/src/stattest/node_modules/@architect/inventory/src/lib/error-fmt.js:15:13)
    at /Users/filmaj/src/stattest/node_modules/@architect/inventory/src/index.js:80:18
```

**Comment by filmaj** [comment]
I have a draft PR for this up here, with as a starting point, a failing test: https://github.com/architect/inventory/pull/80

**Comment by filmaj** [comment]
I just pushed `@architect/architect` 11.2.2 tag; should be live shortly and that version should resolve this issue.
