### ISSUE TITLE
Confusing errors when S3 bucket exists in another account

### ISSUE THREAD

**Issue by sentience** [architect/architect#174]
1. Deploy an arc app with static assets to one AWS account.
2. Deploy the same app to a different AWS account.
3. Errors like this are displayed:
    ```
    { AccessDenied: Access Denied
        at Request.extractError (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/services/s3.js:580:35)
        at Request.callListeners (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
        at Request.emit (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
        at Request.emit (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/request.js:683:14)
        at Request.transition (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /Users/kyank/code/facewall2/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/request.js:685:12)
        at Request.callListeners (/Users/kyank/code/facewall2/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      message: 'Access Denied',
      code: 'AccessDenied',
      region: null,
      time: 2018-10-25T07:29:14.657Z,
      requestId: 'A604E12228FDDD3E',
      extendedRequestId: 'qFOJsnDJi359+epj92mfD4ywYIcSUHttqaMrmC16qRg0ns+9xy9Km07/wlyd22MT7srxSfvZ/0c=',
      cfId: undefined,
      statusCode: 403,
      retryable: false,
      retryDelay: 57.98809804139171 }
    ```

**Expected behavior**
A nicer error like “could not create S3 bucket your-app-production – perhaps it already exists and belongs to another AWS account?”

**Comment by brianleroux** [comment]
thx for this! published in `@architect/architect@5.8.4`
