### ISSUE TITLE
npx dns route53 tries to use aws profile xxx

### ISSUE THREAD

**Issue by retrohacker** [architect/architect#286]
**Describe the bug**

I've been developing using `npx create` and `npx deploy` all day without any problems. But when I just ran `npx dns route53` I got the output:

```
{ CredentialsError: Missing credentials in config
    at SharedIniFileCredentials.load (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:124:11)
    at SharedIniFileCredentials.coalesceRefresh (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/credentials.js:205:12)
    at SharedIniFileCredentials.refresh (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:190:10)
    at SharedIniFileCredentials.get (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/credentials.js:122:12)
    at getAsyncCredentials (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/config.js:362:24)
    at Config.getCredentials (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/config.js:382:9)
    at Request.VALIDATE_CREDENTIALS (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/event_listeners.js:81:26)
    at Request.callListeners (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/retrohacker/Development/dockeri.co/node_modules/aws-sdk/lib/request.js:683:14)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: 2019-01-30T23:27:18.798Z,
  originalError:
   { message: 'Could not load credentials from SharedIniFileCredentials',
     code: 'CredentialsError',
     time: 2019-01-30T23:27:18.797Z,
     originalError:
      { message: 'Profile xxx not found',
        code: 'SharedIniFileCredentialsProviderFailure',
        time: 2019-01-30T23:27:18.792Z } } }
```

Based on the original error `Profile xxx not found`, I figured it was looking for the wrong profile (`xxx` for some reason!).

I decided to add a `[xxx]` entry to my `~/.aws/credentials` file w/ the same values as the `default` entry, and re-ran `npx dns route53` and it worked!

**To Reproduce**
1. Create an `.arc` file with a domain
2. run `npx dns route53`

**Expected behavior**
I expected it to use the profile `default`

**Desktop (please complete the following information):**
 - OS: `Linux jigglypuff 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

**Additional context**

**Comment by neilhoff** [comment]
I can confirm that this is happening with `npx dns`.
The fix where you add `[xxx]` with the same values as default worked as well.

I am on Windows 10.

**Comment by brianleroux** [comment]
Hey there, looks like you are missing AWS_PROFILE which can be set in your shell or by adding an `@aws` section to your `.arc` file. Going to add better error messaging for this!
