### ISSUE TITLE
npx dns bug

### ISSUE THREAD

**Issue by crtr0** [architect/architect#374]
Had issues running both `npx dns` and `npx dns route53`. Had an existing DNS set-up already defined (alpha.fizbuz.com) and was trying to change the domain.

Output from running `npx dns route53` below:

```
{ UnknownEndpoint: Inaccessible host: `route53domains.us-west-2.amazonaws.com'. This service may not be available in the `us-wes
t-2' region.
    at Request.ENOTFOUND_ERROR (/Users/crabasa/Code/fizbuz-arc/node_modules/aws-sdk/lib/event_listeners.js:486:46)
    at Request.callListeners (/Users/crabasa/Code/fizbuz-arc/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/crabasa/Code/fizbuz-arc/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/crabasa/Code/fizbuz-arc/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error (/Users/crabasa/Code/fizbuz-arc/node_modules/aws-sdk/lib/event_listeners.js:325:22)
    at ClientRequest.<anonymous> (/Users/crabasa/Code/fizbuz-arc/node_modules/aws-sdk/lib/http/node.js:93:19)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
  message: 'Inaccessible host: `route53domains.us-west-2.amazonaws.com\'. This service may not be available in the `us-west-2\' region.',
  code: 'UnknownEndpoint',
  region: 'us-west-2',
  hostname: 'route53domains.us-west-2.amazonaws.com',
  retryable: true,
  originalError: 
   { Error: getaddrinfo ENOTFOUND route53domains.us-west-2.amazonaws.com route53domains.us-west-2.amazonaws.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
     message: 'getaddrinfo ENOTFOUND route53domains.us-west-2.amazonaws.com route53domains.us-west-2.amazonaws.com:443',
     code: 'NetworkingError',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'route53domains.us-west-2.amazonaws.com',
     host: 'route53domains.us-west-2.amazonaws.com',
     port: 443,
     region: 'us-west-2',
     retryable: true,
     time: 2019-05-03T15:50:34.054Z },
  time: 2019-05-03T15:50:34.054Z }
```

**Comment by ryanblock** [comment]
@crtr0 just want to confirm, your `@aws` was set to `region us-west-2` yes? Or was it not set at all in your `.arc` file (and not present in your local system env vars)?

**Comment by crtr0** [comment]
`AWS_REGION=us-west-2` is in my env vars. I didn't know it could be set in `.arc`. What's the best practice here?

**Comment by ryanblock** [comment]
Either is fine! I find having that set in the project manifest makes debugging a bit easier but they're the same.

**Comment by brianleroux** [comment]
Just verified DNS and its working. We need better error messages for missing/bad creds and/or no network access (appears to be the cause here).
