### ISSUE TITLE
TypeError when deploying to stage

### ISSUE THREAD

**Issue by dawnerd** [architect/architect#400]
Not really sure what's up with this one. Seems similar to #369 possibly (same error). Any ideas on debugging this further?

```
deploying to 
        app ⌁ xxxxxxxx
     region ⌁ us-east-1
    profile ⌁ xxxx
    version ⌁ 5.9.2

●∙∙ Preparing 4 Functions: Copying src/shared into Functions...
src/http/get-index ........ xxxxxxxx-staging-get-index ........ 0.20 mb
src/http/get-xxxxxxxx ..... xxxxxxxx-staging-get-xxxxxxxx ..... 3.17 mb
src/http/get-xxxxxxxxxx ... xxxxxxxx-staging-get-xxxxxxxxxx ... Creating
src/http/post-xxxxxxx ..... xxxxxxxx-staging-post-xxxxxxx ..... Creating

https://<hidden>.execute-api.us-east-1.amazonaws.com/staging


/Users/troy/Projects/secret-project/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'length' of undefined
    at stringify (/Users/troy/Projects/secret-project/node_modules/@architect/architect/src/deploy/helpers/delta.js:131:15)
    at delta (/Users/troy/Projects/secret-project/node_modules/@architect/architect/src/deploy/helpers/delta.js:58:13)
    at Array.<anonymous> (/Users/troy/Projects/secret-project/node_modules/@architect/architect/src/deploy/lambda-all/03-report.js:24:11)
    at each (/Users/troy/Projects/secret-project/node_modules/run-series/index.js:19:24)
    at _gotUrl (/Users/troy/Projects/secret-project/node_modules/@architect/architect/src/deploy/helpers/report.js:75:7)
    at Response._getRestApis (/Users/troy/Projects/secret-project/node_modules/@architect/architect/src/deploy/helpers/get-url.js:32:11)
    at Request.<anonymous> (/Users/troy/Projects/secret-project/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/troy/Projects/secret-project/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/troy/Projects/secret-project/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/troy/Projects/secret-project/node_modules/aws-sdk/lib/request.js:683:14)
```

```
@http
get /
get /xxxxxxxx
get /xxxxxxxxxx
post /xxxxxxx
```

**Comment by dawnerd** [comment]
Managed to figure it out. Turns out we didn't run `npx create` using the same credentials used for deploy. Might be something that can be improved when that error happens. Maybe have an inventory run/check before deploying?

**Comment by ryanblock** [comment]
Ah, that'll do it.

Inventory does run and check before deploying – this is why it was attempting to create those resources it found missing.

Not sure how we'd guard against something like this.
