### ISSUE TITLE
Error: spawn E2BIG when handling uploaded files

### ISSUE THREAD

**Issue by dawnerd** [architect/architect#639]
I have a simple function setup that accepts an uploaded file (that will later be moved to s3) but sandbox crashes with `Error: spawn E2BIG` right away.

```
[0] internal/child_process.js:366
[0]     throw errnoException(err, 'spawn');
[0]     ^
[0] 
[0] Error: spawn E2BIG
[0]     at ChildProcess.spawn (internal/child_process.js:366:11)
[0]     at spawn (child_process.js:551:9)
[0]     at spawnChild (/Users/troy/Projects/<snip>/node_modules/@architect/sandbox/src/invoke-lambda/spawn.js:12:15)
[0]     at done (/Users/troy/Projects/<snip>/node_modules/@architect/sandbox/src/invoke-lambda/run-in-node.js:12:7)
[0]     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Steps to reproduce**
1. Any post function, mine has literally nothing in it but the default code generated from init.
2. Post a file to the path

**Expected behavior**
Body data should contain the file contents

**Additional context**

Did some googlin' and there might need to be a change to how sandbox passes data: https://stackoverflow.com/a/44091211

https://github.com/architect/sandbox/blob/master/src/invoke-lambda/spawn.js#L14

Should also mention we're using:
sandbox@1.4.3
architect@6.0.13
node v10.16.0
macos catalina

.arc
```
@app
testapp

@cdn
@static
fingerprint true

@http
get /
post /upload

@aws
profile testprofile
region us-east-1
bucket test-arc-upload
```

**Comment by patrikengborg** [comment]
I also have this problem. Any progress on this?

**Comment by ryanblock** [comment]
Good news, got the issue isolated but it'll take me a bit of time to figure out how to solve it. Thanks for your patience!

**Comment by ryanblock** [comment]
Alright, RC is cut, please give it a whirl! `npm i @architect/sandbox@RC` (version is `1.8.2-RC.0`). PR is here: https://github.com/architect/sandbox/pull/303/files

**Comment by ryanblock** [comment]
Mainlined in Sandbox, and will be mainlined today in Architect `6.2.6`.
