### ISSUE TITLE
arc env error when attempting to write variable with leading upper case letter

### ISSUE THREAD

**Issue by rbuckingham** [architect/architect#669]
**Describe the issue**
Trying to add an environment variable with arc env

**Steps to reproduce**
```arc env testing LOG_LEVEL DEBUG```

**Expected behavior**
variable LOG_LEVEL successfully saved as DEBUG

**Screenshots**
```
(venv) ➜  myapp git:(master) ✗ arc env testing LOG_LEVEL DEBUG
         App ⌁ myapp
      Region ⌁ us-west-2
     Profile ⌁ richard
     Version ⌁ Architect 6.2.0
         cwd ⌁ /Users/richard/Documents/projects/myapp

env failed! invalid argument, value must be alphanumeric
Error: invalid argument, value must be alphanumeric
    at Function._put [as add] (/usr/local/lib/node_modules/@architect/architect/node_modules/@architect/env/src/_add.js:33:14)
    at Array.adds (/usr/local/lib/node_modules/@architect/architect/node_modules/@architect/env/index.js:39:24)
    at runSeries (/usr/local/lib/node_modules/@architect/architect/node_modules/run-series/index.js:22:33)
    at Object.env (/usr/local/lib/node_modules/@architect/architect/node_modules/@architect/env/index.js:37:5)
    at run (/usr/local/lib/node_modules/@architect/architect/src/index.js:50:20)
    at main (/usr/local/lib/node_modules/@architect/architect/src/index.js:91:5)
    at /usr/local/lib/node_modules/@architect/architect/src/index.js:100:11
    at Object.<anonymous> (/usr/local/lib/node_modules/@architect/architect/src/index.js:101:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Desktop**
zsh on OSX 10.15.13

**Comment by ryanblock** [comment]
Ew! Thanks, will peep ASAP!

**Comment by ryanblock** [comment]
Hey, let me know if you think this will do the trick? https://github.com/architect/env/pull/120/ (Many shells intercept a lot of other characters, but I'm open to expanding the valid char set further, too.)

**Comment by ryanblock** [comment]
Fix will ship in the next `@architect/architect` release!
