### ISSUE TITLE
5.x can't deploy

### ISSUE THREAD

**Issue by retrohacker** [architect/architect#708]
**Describe the issue**
A few days ago deployments stopped working on 5.x with 

```
Error The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
```

It doesn't seem like 5.x honors the `.arc` or `.arc-config` `runtime` field. I've tried setting:

```
@aws
runtime nodejs12.x
```

In `.arc` to no avail.

**Comment by ryanblock** [comment]
That's not good, will investigate and report back asap.

**Comment by ryanblock** [comment]
Hey there, please post the version you're using? >= `5.9.35` should be fine for post-`nodejs8.10` resource management.

You may need to run `npx config --apply` to update to the current default (`nodejs12.x`).

**Comment by retrohacker** [comment]
Heya @ryanblock! Thank you fro responding!

I'm running `5.9.37`

My `.arc` file:

```
@aws
runtime nodejs12.x
region us-west-2
profile default

@app
website

@domain
blankenship.io

@http
get /
get /date/:year
get /date/:year/:month
get /file/:file
get /rss/:version
get /atom/:version
get /json/:version

@static
staging blankenshipio-static-assets-staging
production blankenshipio-static-assets-production
```

Output of `npx config --apply`

```
        app ⌁ website
     region ⌁ us-west-2
    profile ⌁ default
    version ⌁ 5.9.37

```

and output of `npx deploy`

```        app ⌁ website
     region ⌁ us-west-2
    profile ⌁ default
    version ⌁ 5.9.37

✓ Static asset fingerpringing disabled
✓ Orphaned file pruning disabled
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/deepwork.jpg
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/demonhauntedworld.jpg
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_changes_things_slide1.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_changes_things_slide2.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_changes_things_slide3.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_changes_things_slide4.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_changes_things_slide5.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_owning_stack_slide1.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_owning_stack_slide2.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_owning_stack_slide3.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_owning_stack_slide4.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_owning_stack_slide5.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/docker_profile.svg
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/favicon-16x16.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/favicon-32x32.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/favicon-96x96.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/favicon.ico
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/gettingreal.jpg
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/gnulinuxprogramming.jpg
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/howlinuxworks.jpg
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/intelligentinvestor.jpg
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/what_docker_is_slide1.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/what_docker_is_slide2.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/what_docker_is_slide3.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/what_docker_is_slide4.png
[Not modified] https://blankenshipio-static-assets-production.s3.us-west-2.amazonaws.com/whywesleep.jpg
✓ Success! Deployed static assets from public/
∙∙∙ Preparing 7 Functions: Installing dependencies in 7 Functions
∙●∙ Preparing 7 Functions: Copying src/shared into Functions...
✓ Success! Installed all dependencies in 2743ms
●∙∙ Deploying 7 Functions: Updating Lambdas...

deploy website-production-get-date-000year-000month failed
{ InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
    at Object.extractError (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.',
  code: 'InvalidParameterValueException',
  time: 2020-03-11T16:50:11.485Z,
  requestId: '70608a06-b796-4f22-bac1-df5ce962ed5b',
  statusCode: 400,
  retryable: false,
  retryDelay: 18.07760989462075 }
Error The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
    at Object.extractError (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/retrohacker/Development/new_website/node_modules/aws-sdk/lib/request.js:685:12)
```

And a recording if that helps: https://asciinema.org/a/MqWXWiCqTk3Dvazb1EAPV0KQq

**Comment by brianleroux** [comment]
Looks like default runtime is too low for AWS. Can you try adding a `.arc-config` to the functions with:

```
@aws 
runtime nodejs12.x
```

And running `npx config apply` ?
