### ISSUE TITLE
Sandbox should ignore PointInTimeRecovery table option

### ISSUE THREAD

**Issue by filmaj** [architect/architect#892]
**Describe the issue**
https://arc.codes/primitives/tables#recovery should be ignored by sandbox so that it doesn't try to create a table with the PointInTimeRecovery attribute being used as a table field.

**Steps to reproduce**

```
09:25:08 in ~/src/tmpython
➜ cat app.arc && arc sandbox
@app
init

@http
get /

@scheduled
cleanup rate(1 day)

@tables
wines
  id *String
  PointInTimeRecovery true

# @aws
# profile default
# region us-west-1

         App ⌁ init
      Region ⌁ us-east-2
     Profile ⌁ default
     Version ⌁ Architect 6.5.2
         cwd ⌁ /Users/filmaj/src/tmpython

✓ Sandbox Found Architect project manifest, starting up
✓ Sandbox Project files hydrated into functions
/Users/filmaj/src/architect/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error [TypeError]: attr[k].replace is not a function
    at /Users/filmaj/src/architect/node_modules/@architect/sandbox/src/db/create-table/_get-attribute-definitions.js:6:38
    at Array.forEach (<anonymous>)
    at getAttributeDefinitions (/Users/filmaj/src/architect/node_modules/@architect/sandbox/src/db/create-table/_get-attribute-definitions.js:3:21)
    at Response._tables (/Users/filmaj/src/architect/node_modules/@architect/sandbox/src/db/create-table/_create-table.js:26:33)
    at Request.<anonymous> (/Users/filmaj/src/architect/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/filmaj/src/architect/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/filmaj/src/architect/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/filmaj/src/architect/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/filmaj/src/architect/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/filmaj/src/architect/node_modules/aws-sdk/lib/state_machine.js:14:12) {
  code: 'TypeError',
  time: 2020-06-26T13:25:37.814Z
}
```

**Expected behavior**
Ignore PointInTimeRecovery attribute, add to `_remove-ttl-and-lambda` module.

**Additional context**
I'd suggest we also rename this module inside sandbox as it handles more than TTL and "Lambda" (which I think is meant to handle the Streaming ability?) now (i.e. encrypt, PointInTimeRecovery, I'm sure more will come up too).

This was also spun out of https://github.com/architect/sandbox/pull/340 / architect/architect#785

**Comment by ryanblock** [comment]
I'm pretty sure this is resolved by the Inventory impl in 8.3!
