### ISSUE TITLE
App namespace is not validated, but is mandatory for deployment

### ISSUE THREAD

**Issue by pchinjr** [architect/architect#951]
**Describe the issue**
@app value can be empty and fail deploy without meaningful error. 

**Steps to reproduce**
arc init and deploy the following app.arc file 
```md
@app

@http
get /
```

**Expected behavior**
Expected validation to fail during deploy, saying "Can not deploy without @app namespace"

**Additional context**
Specific error on the terminal is: 
```bash
deploy failed! Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at Object.toLogicalID (/usr/local/lib/node_modules/@architect/architect/node_modules/@architect/utils/to-logical-id/index.js:5:13)
    at Object.samDeploy [as sam] (/usr/local/lib/node_modules/@architect/architect/node_modules/@architect/deploy/src/sam/index.js:33:28)
    at Object.cmd [as deploy] (/usr/local/lib/node_modules/@architect/architect/node_modules/@architect/deploy/cli.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/usr/local/lib/node_modules/@architect/architect/src/index.js:53:5)
    at async main (/usr/local/lib/node_modules/@architect/architect/src/index.js:96:5)
    at async /usr/local/lib/node_modules/@architect/architect/src/index.js:105:5
```

**Comment by ryanblock** [comment]
This will be resolved in Inventory 1.4 and whichever Arc release incorporates that (either 8.7 or 9.0)!
